//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreProcedureWithEF.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetail
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string AddressId { get; set; }
    
        public virtual Address Address { get; set; }
    }   
}
