//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreProcedureWithEF.EntityObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeEntities : DbContext
    {
        public EmployeeEntities()
            : base("name=EmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<EmpDetail> EmpDetails { get; set; }
    
        public virtual ObjectResult<SelectEmployee_Sp_Result> SelectEmployee_Sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectEmployee_Sp_Result>("SelectEmployee_Sp");
        }
    
        public virtual ObjectResult<EmployeeDetail> SelectEmployee_Sp1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeDetail>("SelectEmployee_Sp1");
        }
    
        public virtual ObjectResult<EmployeeDetail> SelectEmployee_Sp1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeDetail>("SelectEmployee_Sp1", mergeOption);
        }
    
        public virtual ObjectResult<SelectEmployee3_Sp_Result> SelectEmployee3_Sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectEmployee3_Sp_Result>("SelectEmployee3_Sp");
        }
    
        public virtual ObjectResult<EmpDetail> SelectEmployee3_Sp1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpDetail>("SelectEmployee3_Sp1");
        }
    
        public virtual ObjectResult<EmpDetail> SelectEmployee3_Sp1(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpDetail>("SelectEmployee3_Sp1", mergeOption);
        }        
    }
}
